version: "3.3"

services:
        eventsonestop:
                build:
                        context: .
                        dockerfile: Dockerfile
                extra_hosts:
                        - "host.docker.internal:host-gateway"
                ports:
                        - "9343:8008"
                env_file:
                        - .env
                volumes:
                        - eventsimages:/usr/src/app/uploads

networks:
    default:
        external:
            name: backend_default

volumes:
        eventsimages:
